/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=cloudflare.env.example --include-runtime=false --env-interface=CloudflareEnv src/types/cloudflare-env.d.ts` (hash: 78e04e2bff836bc741c1b77f555bd50c)
interface __BaseEnv_CloudflareEnv {
	MEDIA: R2Bucket;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
